### ISSUE TITLE
  File "build/bdist.macosx-10.12-x86_64/egg/hupu.py", line 94     print("  位置", end="")                          ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Paulswith** [chenjiandongx/HupuLive#1]
➜  Installation cd HupuLive && python setup.py install
running install
running bdist_egg
running egg_info
creating HupuLive.egg-info
writing HupuLive.egg-info/PKG-INFO
writing top-level names to HupuLive.egg-info/top_level.txt
writing dependency_links to HupuLive.egg-info/dependency_links.txt
writing entry points to HupuLive.egg-info/entry_points.txt
writing manifest file 'HupuLive.egg-info/SOURCES.txt'
reading manifest file 'HupuLive.egg-info/SOURCES.txt'
writing manifest file 'HupuLive.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.12-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
copying hupu.py -> build/lib
creating build/bdist.macosx-10.12-x86_64
creating build/bdist.macosx-10.12-x86_64/egg
copying build/lib/hupu.py -> build/bdist.macosx-10.12-x86_64/egg
byte-compiling build/bdist.macosx-10.12-x86_64/egg/hupu.py to hupu.pyc
  File "build/bdist.macosx-10.12-x86_64/egg/hupu.py", line 94
    print("  位置", end="")
                         ^
SyntaxError: invalid syntax

creating build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying HupuLive.egg-info/PKG-INFO -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying HupuLive.egg-info/SOURCES.txt -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying HupuLive.egg-info/dependency_links.txt -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying HupuLive.egg-info/entry_points.txt -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying HupuLive.egg-info/top_level.txt -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/HupuLive-1.2-py2.7.egg' and adding 'build/bdist.macosx-10.12-x86_64/egg' to it
removing 'build/bdist.macosx-10.12-x86_64/egg' (and everything under it)
Processing HupuLive-1.2-py2.7.egg
Copying HupuLive-1.2-py2.7.egg to /usr/local/lib/python2.7/site-packages
Adding HupuLive 1.2 to easy-install.pth file
Installing hupu script to /usr/local/bin

Installed /usr/local/lib/python2.7/site-packages/HupuLive-1.2-py2.7.egg
Processing dependencies for HupuLive==1.2
Finished processing dependencies for HupuLive==1.2
➜  HupuLive git:(master) hupu -h
Traceback (most recent call last):
  File "/usr/local/bin/hupu", line 11, in <module>
    load_entry_point('HupuLive==1.2', 'console_scripts', 'hupu')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/HupuLive-1.2-py2.7.egg/hupu.py", line 94
    print("  位置", end="")
                         ^
SyntaxError: invalid syntax
➜  HupuLive git:(master)

**Comment by chenjiandongx** [comment]
应该是 Python3 中的 print 变成了内置函数而不是 Python2 中的语句造成的 这个项目是在 Python3 下测试的，你自己把 print 修改一下成 Python2 的格式再安装试试看？  
类似 ``` print " 位置",```  ? 
Python3 在字符格式上和 Python2 也有点不同，不知道还会不会出现其他问题

**Comment by xinc2** [comment]
add "from __future__ import print_function" at the begining of hupu.py if you work in python2

**Comment by chenjiandongx** [comment]
@Paulswith May be you could try to do as @heaven0419 comment？
